export const FETCH_HEADER_DATA = 'FETCH_HEADER_DATA';
export const UPDATE_HEADER_DATA = 'UPDATE_HEADER_DATA';
export const FETCH_IMAGES_DATA = 'FETCH_IMAGES_DATA';
export const UPDATE_IMAGES_DATA = 'UPDATE_IMAGES_DATA';
export const ADD_NEW_IMAGE = 'ADD_NEW_IMAGE';
export const UPDATE_PAGE_DATA = 'UPDATE_PAGE_DATA';
