import CssBaseline from '@material-ui/core/CssBaseline';
import AppBar from '@material-ui/core/AppBar';
import Typography from '@material-ui/core/Typography';
import Slide from '@material-ui/core/Slide';
import useScrollTrigger from '@material-ui/core/useScrollTrigger';
import { MuiThemeProvider, createMuiTheme, makeStyles } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';
import Toolbar from '@material-ui/core/Toolbar';
import SpeedDial from '@material-ui/lab/SpeedDial';
import Container from '@material-ui/core/Container';
import * as Icons from '@material-ui/icons';
import SpeedDialAction from '@material-ui/lab/SpeedDialAction';
import Snackbar from '@material-ui/core/Snackbar';
import MuiAlert from '@material-ui/lab/Alert';

export const PCssBaseline = CssBaseline;
export const PAppBar = AppBar;
export const PTypography = Typography;
export const PSlide = Slide;
export const PuseScrollTrigger = useScrollTrigger;
export const PThemeProvider = MuiThemeProvider;
export const PcreateTheme = createMuiTheme;
export const PButton = Button;
export const PToolbar = Toolbar;
export const PSpeedDial = SpeedDial;
export const PmakeStyles = makeStyles;
export const PContainer = Container;
export const PIcons = Icons;
export const PSpeedDialAction = SpeedDialAction;
export const PSnackbar = Snackbar;
export const PMuiAlert = MuiAlert;
console.log("cc")